### PR TITLE
updating footer js file

### PR DESCRIPTION
**Pull request by syarwick**

### CODE REVIEW

**Comment by syarwick** [comment]
Hi Steve, sorry, should have explained earlier. I'm just updating the js file, but the way I did it made me create a branch and merge request. I'm not sure if there are any real changes but just making sure T4 and the repo are the same

**Comment by stephenravenscraft** [comment]
[like]  Ravenscraft, Stephen reacted to your message:
________________________________

**Comment by stephenravenscraft** [comment]
Do you need another review approval?

Stephen Ravenscraft
Senior Web Designer  •  University Marketing and Communication
111 E. Pearson St., Chicago, IL 60611  •  Water Tower Campus
Loyola University Chicago
1032 W. Sheridan Rd., Chicago, IL 60660
P: 312-915-6367  •  M: 630.750.1986

[cid:93893491-c76a-489b-9b9d-ed0d6d37d8b1]

________________________________

**Comment by syarwick** [comment]
Yes, I'll need an approval please.

**Pull request merged**
